from pathlib import Path

path = Path('/app/experimental_children_v1.py')
text = path.read_text(encoding='utf-8')

# Experimental technical README belongs inside /experimental/.
text = text.replace('_write_readme(final, track, timings, models)', '_write_readme(experimental, track, timings, models)')
text = text.replace('(final / f"{track}_EXPERIMENTAL_REPORT.json")', '(experimental / f"{track}_EXPERIMENTAL_REPORT.json")')
text = text.replace('"schema_version": 2,', '"schema_version": 3,', 1)

old_wind = '''        emit("Running Wind Family Separation", 56)\n        other_parent = root / "other_parent.flac"\n        _copy_as_flac(stems["other"], other_parent)\n        t0 = time.monotonic()\n        wind_cmd = ["audio-separator", str(other_parent), "--model_filename", WIND_MODEL, "--model_file_dir", str(audio_separator_model_dir), "--output_dir", str(wind_out), "--output_format", "FLAC"]\n        wind = subprocess.run(wind_cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, timeout=timeout)\n        timings["wind_uvr"] = round(time.monotonic() - t0, 3)\n        wind_files = _copy_audio_tree(wind_out, experimental, f"{track}_wind_uvr") if wind.returncode == 0 else []\n\n        emit("Running Saxophone Specialist Separation", 74)\n        t0 = time.monotonic()\n        sax_cmd = ["python", "-m", "demucs", "--repo", str(SAX_MODEL_DIR), "-n", SAX_MODEL, "-o", str(sax_out), str(other_parent)]\n        sax = subprocess.run(sax_cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, timeout=timeout)\n        timings["sax_demucs"] = round(time.monotonic() - t0, 3)\n        sax_files = _copy_audio_tree(sax_out, experimental, f"{track}_sax_specialist") if sax.returncode == 0 else []\n'''

new_wind = '''        emit("Running Wind Family Separation", 56)\n        other_parent = root / "other_parent.flac"\n        _copy_as_flac(stems["other"], other_parent)\n        t0 = time.monotonic()\n        wind_cmd = ["audio-separator", str(other_parent), "--model_filename", WIND_MODEL, "--model_file_dir", str(audio_separator_model_dir), "--output_dir", str(wind_out), "--output_format", "FLAC"]\n        wind = subprocess.run(wind_cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, timeout=timeout)\n        timings["wind_uvr"] = round(time.monotonic() - t0, 3)\n\n        wind_files: list[str] = []\n        woodwind_path = None\n        wind_residual_path = None\n        if wind.returncode == 0:\n            candidates = [p for p in wind_out.rglob("*") if p.is_file() and p.suffix.lower() in {".wav", ".flac", ".mp3"}]\n            woodwind_src = next((p for p in candidates if "woodwind" in p.name.lower() and "no_woodwind" not in p.name.lower() and "no woodwind" not in p.name.lower() and "no-woodwind" not in p.name.lower()), None)\n            residual_src = next((p for p in candidates if "no_woodwind" in p.name.lower() or "no woodwind" in p.name.lower() or "no-woodwind" in p.name.lower()), None)\n            if woodwind_src:\n                woodwind_path = experimental / f"{track}_wind_woodwinds.flac"\n                _copy_as_flac(woodwind_src, woodwind_path)\n                wind_files.append(woodwind_path.name)\n            if residual_src:\n                wind_residual_path = experimental / f"{track}_wind_residual.flac"\n                _copy_as_flac(residual_src, wind_residual_path)\n                wind_files.append(wind_residual_path.name)\n            if not woodwind_src and not residual_src:\n                wind_files = _copy_audio_tree(wind_out, experimental, f"{track}_wind_uvr")\n\n        emit("Running Saxophone Specialist Separation", 74)\n        t0 = time.monotonic()\n        sax_input = woodwind_path if woodwind_path and woodwind_path.is_file() else other_parent\n        sax_cmd = ["python", "-m", "demucs", "--repo", str(SAX_MODEL_DIR), "-n", SAX_MODEL, "-o", str(sax_out), str(sax_input)]\n        sax = subprocess.run(sax_cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, timeout=timeout)\n        timings["sax_demucs"] = round(time.monotonic() - t0, 3)\n        sax_files = _copy_audio_tree(sax_out, experimental, f"{track}_sax_specialist") if sax.returncode == 0 else []\n'''

if old_wind not in text:
    raise RuntimeError('Could not locate wind/sax experiment block')
text = text.replace(old_wind, new_wind, 1)

old_report_wind = '''            "wind": {"ok": wind.returncode == 0, "files": wind_files, "runtime_tail": "\\n".join((wind.stdout or "").splitlines()[-25:]) if wind.returncode else ""},\n            "saxophone": {"ok": sax.returncode == 0, "files": sax_files, "runtime_tail": "\\n".join((sax.stdout or "").splitlines()[-25:]) if sax.returncode else ""},\n'''
new_report_wind = '''            "wind": {\n                "ok": wind.returncode == 0,\n                "architecture": "Other parent -> Woodwinds + Wind Residual",\n                "woodwinds_file": woodwind_path.name if woodwind_path else None,\n                "residual_file": wind_residual_path.name if wind_residual_path else None,\n                "files": wind_files,\n                "runtime_tail": "\\n".join((wind.stdout or "").splitlines()[-25:]) if wind.returncode else "",\n            },\n            "saxophone": {\n                "ok": sax.returncode == 0,\n                "input": "Woodwinds child" if woodwind_path else "Other parent fallback",\n                "files": sax_files,\n                "runtime_tail": "\\n".join((sax.stdout or "").splitlines()[-25:]) if sax.returncode else "",\n            },\n'''
if old_report_wind not in text:
    raise RuntimeError('Could not locate wind report block')
text = text.replace(old_report_wind, new_report_wind, 1)

old_pack = '''        emit("Packaging Parent and Experimental Stems", 92)\n        archive = root / f"{track}_parent_plus_experimental.zip"\n        with zipfile.ZipFile(archive, "w", compression=zipfile.ZIP_STORED) as bundle:\n            for p in sorted(final.rglob("*")):\n                if p.is_file():\n                    bundle.write(p, arcname=str(p.relative_to(final)))\n'''

new_pack = '''        # Keep the root README in the established production format.\n        from master_pack import write_litelabs_readme, format_elapsed, format_bytes\n        included_readme = [\n            "Vocals", "Drums", "Bass", "Guitar", "Piano / Keys",\n            "Synths / Strings / Other", "Clean Instrumental",\n        ]\n        elapsed_text = format_elapsed(time.monotonic() - started)\n        write_litelabs_readme(\n            final / "README.txt", track, "flac", "calculating", elapsed_text,\n            "v3_beta_experimental",\n            "BS-RoFormer parent stems retained; child separators are being validated in /experimental/",\n            included_readme, [],\n        )\n\n        emit("Packaging Parent and Experimental Stems", 92)\n        archive = root / f"{track}_parent_plus_experimental.zip"\n\n        def make_archive() -> None:\n            if archive.exists():\n                archive.unlink()\n            with zipfile.ZipFile(archive, "w", compression=zipfile.ZIP_STORED) as bundle:\n                for p in sorted(final.rglob("*")):\n                    if p.is_file():\n                        bundle.write(p, arcname=str(p.relative_to(final)))\n\n        make_archive()\n        final_size = format_bytes(archive.stat().st_size)\n        write_litelabs_readme(\n            final / "README.txt", track, "flac", final_size, elapsed_text,\n            "v3_beta_experimental",\n            "BS-RoFormer parent stems retained; child separators are being validated in /experimental/",\n            included_readme, [],\n        )\n        make_archive()\n'''
if old_pack not in text:
    raise RuntimeError('Could not locate packaging block')
text = text.replace(old_pack, new_pack, 1)

path.write_text(text, encoding='utf-8')
print('LiteLABS family-first wind and v3 experimental packaging patch applied')
