from pathlib import Path

path = Path('/app/handler.py')
text = path.read_text(encoding='utf-8')

old = '''    def progress(message: str, percent: int) -> None:\n        post_progress(progress_url, progress_token, progress_job_id, message, percent)\n\n    mode = str(payload.get("mode") or "routed_extraction_v1").strip()\n    if mode == "routed_extraction_v1":\n        try:\n            from routed_extraction_v1 import build_routed_extraction_v1\n            result = build_routed_extraction_v1(payload, progress=progress)\n            if result.get("ok"):\n                result["production"] = True\n                result.pop("research_only", None)\n                result.pop("warning", None)\n            return result\n        except Exception as exc:\n            post_progress(progress_url, progress_token, progress_job_id, f"Worker error: {exc}", 100)\n            return {"ok": False, "mode": mode, "error": str(exc), "error_type": exc.__class__.__name__}\n'''

new = '''    def progress(message: str, percent: int) -> None:\n        post_progress(progress_url, progress_token, progress_job_id, message, percent)\n\n    def routed_progress(message: str, percent: int) -> None:\n        lower = str(message or "").lower()\n        if "resolving baked separation models" in lower or "downloading fixed sw" in lower:\n            clean = "Initiating stem separation"\n        elif "downloading source" in lower:\n            clean = "Downloading source audio"\n        elif "preparing source" in lower:\n            clean = "Preparing source audio"\n        elif "primary bs-roformer" in lower or "running primary separation" in lower:\n            clean = "Running primary stem separation"\n        elif "drumsep" in lower or "decomposing drum parent" in lower:\n            clean = "Running DrumSep Decomposition"\n        elif "mega53" in lower or "decomposing other" in lower:\n            clean = "Running Mega53 Decomposition"\n        elif "packaging" in lower:\n            clean = "Packaging stem pack"\n        elif "uploading routed stem pack" in lower:\n            clean = "Uploading stem pack"\n        elif "routed extraction complete" in lower:\n            clean = "Stem extraction complete"\n        else:\n            clean = str(message or "Processing stems")\n        post_progress(progress_url, progress_token, progress_job_id, clean, percent)\n\n    mode = str(payload.get("mode") or "routed_extraction_v1").strip()\n    if mode == "routed_extraction_v1":\n        try:\n            from routed_extraction_v1 import build_routed_extraction_v1\n            routed_payload = dict(payload)\n            allow_unvalidated = bool(payload.get("allow_unvalidated_specialist_children", False))\n            if not allow_unvalidated:\n                # Listening validation showed that reconstruction closure alone does not\n                # guarantee clean or correctly-owned specialist children. Continue running\n                # the specialist stages for production telemetry, but retain the cleaner\n                # BS-RoFormer parent stems until a perceptual/usefulness gate is proven.\n                routed_payload["drum_reconstruction_cosine_gate"] = 2.0\n                routed_payload["child_rms_gate_dbfs"] = 1.0\n            result = build_routed_extraction_v1(routed_payload, progress=routed_progress)\n            if result.get("ok"):\n                result["production"] = True\n                result["specialist_children_exported"] = allow_unvalidated\n                result.pop("research_only", None)\n                result.pop("warning", None)\n            return result\n        except Exception as exc:\n            post_progress(progress_url, progress_token, progress_job_id, f"Worker error: {exc}", 100)\n            return {"ok": False, "mode": mode, "error": str(exc), "error_type": exc.__class__.__name__}\n'''

if old not in text:
    raise RuntimeError('Could not locate routed production handler block')

text = text.replace(old, new, 1)
path.write_text(text, encoding='utf-8')
print('LiteLABS production quality/status patch applied')
