from pathlib import Path

path = Path('/app/experimental_vocal_cross_song_validation.py')
text = path.read_text(encoding='utf-8')

text = text.replace('MODE = "experimental_vocal_cross_song_validation_v7"', 'MODE = "experimental_vocal_cross_song_validation_v8"', 1)
text = text.replace('https://literecords.com/tmp/tears-for-fears-shout.zip', 'https://literecords.com/tmp/4%20non%20blondes%20-%20what%27s%20up%28studio%20stems%29.zip', 1)
text = text.replace('/workspace/litelabs-research/shout_vocal_cross_song_validation_v7.json', '/workspace/litelabs-research/4_non_blondes_vocal_cross_song_validation_v8.json', 1)

old_nonlead = '''    if not nonlead:\n        raise RuntimeError(\n            "Cross-song validation needs at least one non-lead vocal reference to score backing. "\n            f"Lead={lead_name}; vocal-like={[name for name, _ in vocal_like]}"\n        )\n\n    explicit_backing = [(name, audio) for name, audio in nonlead if _is_explicit_backing(name)]\n    backing_inclusive = _sum_audio([audio for _name, audio in nonlead])\n    backing_strict = (\n        _sum_audio([audio for _name, audio in explicit_backing])\n        if explicit_backing else backing_inclusive.copy()\n    )\n    total_vocals = _sum_audio([lead] + [audio for _name, audio in nonlead])\n    core_pair = lead[: min(len(lead), len(backing_strict))] + backing_strict[: min(len(lead), len(backing_strict))]\n\n    refs = {\n        "lead": np.asarray(lead, dtype=np.float32),\n        "backing_strict": np.asarray(backing_strict, dtype=np.float32),\n        "backing_inclusive": np.asarray(backing_inclusive, dtype=np.float32),\n        "core_pair": np.asarray(core_pair, dtype=np.float32),\n        "total_vocals": np.asarray(total_vocals, dtype=np.float32),\n    }\n    meta = {\n        "lead_members": [lead_name],\n        "backing_strict_members": [name for name, _audio in explicit_backing] or [name for name, _audio in nonlead],\n        "backing_inclusive_members": [name for name, _audio in nonlead],\n        "all_vocal_members": [name for name, _audio in vocal_like],\n        "strict_backing_fell_back_to_inclusive": not bool(explicit_backing),\n        "note": (\n            "Lead selection is conservative and must match a lead/main-vocal style name before GPU inference. "\n            "Inclusive backing contains every non-lead vocal-like track."\n        ),\n    }\n'''

new_nonlead = '''    explicit_backing = [(name, audio) for name, audio in nonlead if _is_explicit_backing(name)]\n    has_backing_reference = bool(nonlead)\n    if has_backing_reference:\n        backing_inclusive = _sum_audio([audio for _name, audio in nonlead])\n        backing_strict = (\n            _sum_audio([audio for _name, audio in explicit_backing])\n            if explicit_backing else backing_inclusive.copy()\n        )\n        total_vocals = _sum_audio([lead] + [audio for _name, audio in nonlead])\n        core_pair = lead[: min(len(lead), len(backing_strict))] + backing_strict[: min(len(lead), len(backing_strict))]\n        refs = {\n            "lead": np.asarray(lead, dtype=np.float32),\n            "backing_strict": np.asarray(backing_strict, dtype=np.float32),\n            "backing_inclusive": np.asarray(backing_inclusive, dtype=np.float32),\n            "core_pair": np.asarray(core_pair, dtype=np.float32),\n            "total_vocals": np.asarray(total_vocals, dtype=np.float32),\n        }\n    else:\n        # Some studio packs expose only a single combined vocal reference. Do not fail and\n        # do not invent backing ground truth: score vocal-parent + lead, and explicitly mark\n        # backing metrics ignored/unavailable for this song.\n        refs = {\n            "lead": np.asarray(lead, dtype=np.float32),\n            "total_vocals": np.asarray(lead, dtype=np.float32),\n        }\n\n    meta = {\n        "lead_members": [lead_name],\n        "backing_reference_available": has_backing_reference,\n        "backing_strict_members": ([name for name, _audio in explicit_backing] or [name for name, _audio in nonlead]) if has_backing_reference else [],\n        "backing_inclusive_members": [name for name, _audio in nonlead],\n        "all_vocal_members": [name for name, _audio in vocal_like],\n        "strict_backing_fell_back_to_inclusive": has_backing_reference and not bool(explicit_backing),\n        "backing_fallback": "ignore_backing_metrics" if not has_backing_reference else None,\n        "note": (\n            "Lead selection is conservative and must match a lead/main-vocal style name before GPU inference. "\n            "If no independent non-lead vocal reference exists, backing quality is deliberately ignored rather than fabricated."\n        ),\n    }\n'''

if old_nonlead not in text:
    raise RuntimeError('Could not locate v7 non-lead reference block')
text = text.replace(old_nonlead, new_nonlead, 1)

anchor = '''def _brief(candidate: dict) -> dict:\n'''
helper = '''def _pair_metrics_optional_backing(*, name, input_audio, lead, backing, refs_audio, sr, runtime_seconds, model, route):\n    if "backing_inclusive" in refs_audio and "backing_strict" in refs_audio and "core_pair" in refs_audio:\n        return vb._pair_metrics(\n            name=name, input_audio=input_audio, lead=lead, backing=backing, refs_audio=refs_audio,\n            sr=sr, runtime_seconds=runtime_seconds, model=model, route=route,\n        )\n\n    n = min(len(input_audio), len(lead), len(backing))\n    input_audio = np.asarray(input_audio[:n], dtype=np.float32)\n    lead = np.asarray(lead[:n], dtype=np.float32)\n    backing = np.asarray(backing[:n], dtype=np.float32)\n    pair_sum = lead + backing\n    residual = input_audio - pair_sum\n    result = {\n        "name": name,\n        "model": model,\n        "route": route,\n        "runtime_seconds": round(runtime_seconds, 3),\n        "lead": _score(lead, refs_audio["lead"][: min(n, len(refs_audio["lead"]))], sr),\n        "backing_available": True,\n        "backing_reference_available": False,\n        "backing_metrics_ignored": True,\n        "backing_strict": None,\n        "backing_inclusive": None,\n        "core_pair": None,\n        "input_reconstruction_cosine": round(vb._cos(input_audio, pair_sum), 9),\n        "input_reconstruction_residual_db": round(vb._db(vb._rms(residual) / max(vb._rms(input_audio), 1e-12)), 3),\n        "lead_backing_correlation": round(abs(vb._cos(lead, backing)), 6),\n        "lead_backing_composite": None,\n    }\n    return result\n\n\n'''
if anchor not in text:
    raise RuntimeError('Could not locate brief helper anchor')
text = text.replace(anchor, helper + anchor, 1)
text = text.replace('vb._pair_metrics(', '_pair_metrics_optional_backing(', 3)

text = text.replace('candidate.get("backing_inclusive", {}).get("quality_score")', '(candidate.get("backing_inclusive") or {}).get("quality_score")')
text = text.replace('candidate.get("backing_strict", {}).get("quality_score")', '(candidate.get("backing_strict") or {}).get("quality_score")')

# Sorting must tolerate ignored backing/composite values.
text = text.replace('float(x.get("backing_inclusive_quality") or -1.0)', 'float(x.get("backing_inclusive_quality") if x.get("backing_inclusive_quality") is not None else -1.0)')
text = text.replace('float(x.get("composite") or -1.0)', 'float(x.get("composite") if x.get("composite") is not None else -1.0)')

text = text.replace(
    '"This is the final cross-song validation: current SET baseline, fast SW->Becruily residual, "\n                    "and the Disturbia quality winner 25/75 SW/MelBand->Becruily. No further blend sweep is run."',
    '"Final cross-song validation: current SET baseline, fast SW->Becruily residual, and the Disturbia quality winner "\n                    "25/75 SW/MelBand->Becruily. If a song has no independent backing-vocal reference, backing scoring "\n                    "is ignored for that song while vocal-parent and lead metrics still run."',
    1,
)

path.write_text(text, encoding='utf-8')
print('cross-song validation v8: backing-reference ignore fallback + 4 Non Blondes default applied')
